# Services para los 3 deployments de cdt-pais.
# Kong usa estos hostnames como upstream (ver infra/k8s/borde/kong-config.yaml).
# Formato: cdt-pais-<pais>.linea-verde.svc.cluster.local:8080

---
apiVersion: v1
kind: Service
metadata:
  name: cdt-pais-pe
  namespace: linea-verde
  labels:
    app.kubernetes.io/name: cdt-pais
    app.kubernetes.io/instance: cdt-pais-pe
    app.kubernetes.io/component: CDTXPais
    app.kubernetes.io/part-of: linea-verde-experimento
    pais: pe
spec:
  selector:
    app.kubernetes.io/instance: cdt-pais-pe
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: cdt-pais-mx
  namespace: linea-verde
  labels:
    app.kubernetes.io/name: cdt-pais
    app.kubernetes.io/instance: cdt-pais-mx
    app.kubernetes.io/component: CDTXPais
    app.kubernetes.io/part-of: linea-verde-experimento
    pais: mx
spec:
  selector:
    app.kubernetes.io/instance: cdt-pais-mx
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: cdt-pais-co
  namespace: linea-verde
  labels:
    app.kubernetes.io/name: cdt-pais
    app.kubernetes.io/instance: cdt-pais-co
    app.kubernetes.io/component: CDTXPais
    app.kubernetes.io/part-of: linea-verde-experimento
    pais: co
spec:
  selector:
    app.kubernetes.io/instance: cdt-pais-co
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP
