#!/usr/bin/env python3
"""scripts/bundle_k6.py — bundler trivial de imports relativos para k6.

k6 v0.53 soporta `import` relativo nativo cuando los archivos están en el
filesystem del pod, pero el k6-operator monta UN solo archivo desde un
ConfigMap. Por eso bundleamos in-place: encontramos todos los `import ... from
"./relativo.js"` y reemplazamos por el contenido del archivo importado,
respetando los `export` con un namespacing manual.

Estrategia minimalista (no AST):
  - Resolvemos imports recursivamente.
  - Para cada módulo importado, generamos un IIFE que expone sus exports a
    un objeto namespace.
  - El módulo entry concatena todos los namespaces y reescribe los `import`
    a desestructuraciones desde esos namespaces.

NO es un bundler general — solo cubre los imports planos `from "./x.js"` y
`from "../lib/x.js"` que usamos en load/.
"""

import os
import re
import sys

IMPORT_RE = re.compile(
    r'^\s*import\s+(?:\{([^}]+)\}|\*\s+as\s+([\w$]+)|([\w$]+))\s+from\s+["\'](\.{1,2}/[^"\']+)["\']\s*;?\s*$',
    re.MULTILINE,
)
EXPORT_NAMED_RE = re.compile(
    r'^\s*export\s+(const|let|var|function|class)\s+([\w$]+)', re.MULTILINE
)
EXPORT_LIST_RE = re.compile(r'^\s*export\s+\{([^}]+)\}\s*;?\s*$', re.MULTILINE)


def resolve(path, importer_dir):
    """Resuelve un import relativo a una ruta absoluta normalizada."""
    return os.path.normpath(os.path.join(importer_dir, path))


def parse_module(path, modules, order):
    """Parse recursivo. `modules[path]` = { src, exports, deps }."""
    if path in modules:
        return
    with open(path, "r", encoding="utf-8") as f:
        src = f.read()
    importer_dir = os.path.dirname(path)
    deps = []
    for m in IMPORT_RE.finditer(src):
        named, namespace, default, rel = m.groups()
        sub_path = resolve(rel, importer_dir)
        parse_module(sub_path, modules, order)
        deps.append({
            "path": sub_path,
            "named": [s.strip() for s in named.split(",")] if named else [],
            "namespace": namespace,
            "default": default,
            "raw": m.group(0),
        })
    # Detectar exports.
    exports = set()
    for m in EXPORT_NAMED_RE.finditer(src):
        exports.add(m.group(2))
    for m in EXPORT_LIST_RE.finditer(src):
        for name in m.group(1).split(","):
            name = name.strip().split(" as ")[0].strip()
            if name:
                exports.add(name)
    modules[path] = {"src": src, "exports": exports, "deps": deps}
    order.append(path)


def transform_to_iife(path, info):
    """Transforma un módulo en una IIFE que expone sus exports.

    - Reescribe `import {a,b} from "./x.js"` a `const {a,b} = __MOD__x_js;`.
    - Reescribe `export const x = ...` -> `const x = ...;` y al final agrega
      `return { x, ... }`.
    - El IIFE result se asigna a `const __MOD__path = (function() { ... })();`.
    """
    src = info["src"]
    importer_dir = os.path.dirname(path)
    # Reemplazar imports.
    def replace_import(m):
        named, namespace, default, rel = m.groups()
        sub_path = resolve(rel, importer_dir)
        var = mod_var(sub_path)
        if named:
            return f"const {{{named}}} = {var};"
        if namespace:
            return f"const {namespace} = {var};"
        if default:
            return f"const {default} = {var}.default;"
        return ""
    src2 = IMPORT_RE.sub(replace_import, src)
    # Quitar `export` de declaraciones top-level (los recolectamos al final).
    src2 = re.sub(r'^\s*export\s+(const|let|var|function|class)\b', r'\1', src2, flags=re.MULTILINE)
    # Eliminar `export { ... };` lines del cuerpo.
    src2 = EXPORT_LIST_RE.sub("", src2)
    # Construir el return.
    exports = sorted(info["exports"])
    return_obj = "{" + ", ".join(exports) + "}"
    iife = f"const {mod_var(path)} = (function() {{\n{src2}\nreturn {return_obj};\n}})();\n"
    return iife


def mod_var(path):
    """Variable name para representar el módulo. Estable, basado en el path."""
    base = os.path.basename(path).replace(".", "_").replace("-", "_")
    parent = os.path.basename(os.path.dirname(path))
    return f"__MOD__{parent}__{base}"


def bundle(entry, out):
    modules = {}
    order = []
    abs_entry = os.path.abspath(entry)
    parse_module(abs_entry, modules, order)
    # Generar bundle: emitir en el orden topológico de `order` (dependencias
    # antes que dependientes, gracias a la recursión DFS).
    parts = ["// Generated by scripts/bundle_k6.py — do not edit by hand."]
    parts.append(f"// Entry: {entry}")
    # Emitir módulos no-entry primero.
    for path in order:
        if path == abs_entry:
            continue
        parts.append(transform_to_iife(path, modules[path]))
    # El módulo entry: reemplazamos imports y conservamos el resto.
    entry_info = modules[abs_entry]
    src = entry_info["src"]
    importer_dir = os.path.dirname(abs_entry)
    def replace_import(m):
        named, namespace, default, rel = m.groups()
        sub_path = resolve(rel, importer_dir)
        var = mod_var(sub_path)
        if named:
            return f"const {{{named}}} = {var};"
        if namespace:
            return f"const {namespace} = {var};"
        if default:
            return f"const {default} = {var}.default;"
        return ""
    src2 = IMPORT_RE.sub(replace_import, src)
    parts.append(src2)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    print(f"[bundle_k6] {entry} -> {out}  ({len(modules)} módulos, {sum(len(m['src']) for m in modules.values())} chars)")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("uso: bundle_k6.py <entry.js> <out.js>", file=sys.stderr)
        sys.exit(2)
    bundle(sys.argv[1], sys.argv[2])
